Updated tests of multi-database backup

diff --git a/bin/backup-db b/bin/backup-db
--- a/bin/backup-db
+++ b/bin/backup-db
@@ -2,6 +2,20 @@
 
 source defs.bash
 
+if [ -z $DB_NAME ] && [ -z $PGDATABASE ] ; then
+  echo "Neither DB_NAME or PGDATABASE is set!"
+  exit 1
+fi
+
+if [ -z $DB_NAME ]; then
+  echo "DB_NAME is not set, falling back to PGDATABASE"
+  if [[ $PGDATABASE =~ "," ]]; then
+    echo "PGDATABASE cannot be set to a comma-delimited list!"
+    exit 1
+  fi
+  export DB_NAME=$PGDATABASE
+fi
+
 check-vars "for backup" DB_NAME || exit 1
 
 backup_dir=""
@@ -17,6 +31,8 @@ export PGPORT=${PGPORT:-5432}
 
 databases=$(echo $DB_NAME | tr "," "\n")
 for dbname in $databases ; do
+  # Set postgres environment variables
+  export PGDATABASE=$dbname
   dumpfile=""
   did_something=false
   # We mount local DB_BACKUP_DIR as 
diff --git a/test-backup b/test-backup
--- a/test-backup
+++ b/test-backup
@@ -14,9 +14,16 @@ if [ ${1:-""} == "--no-cleanup" ]; then
   shift
 fi
 
+ntests=0
 run-test() {
   echo ""
-  echo -e "\033[1mTest: $1\033[0m"
+  ntests=$(( ntests + 1 ))
+  printf "\e[0m"
+  tput bold
+  echo "Test $ntests: $1"
+  tput sgr0
+  # Turn to dim
+  printf "\e[2m"
 }
 
 cleanup() {
@@ -29,9 +36,9 @@ cleanup() {
     docker compose rm -f --volumes
   fi
   if (( $returncode )); then
-    echo "Tests failed!"
+    tput setaf 1; echo "Tests failed!"
   else
-    echo "Tests passed!"
+    tput setaf 2; echo "Tests passed!"
   fi
 
   exit $returncode
@@ -40,7 +47,6 @@ cleanup() {
 trap "cleanup" EXIT
 
 export S3_BACKUP_BUCKET="test-bucket"
-export DB_NAME="test_database"
 export PGPORT=5432
 
 function in-container {
@@ -84,7 +90,6 @@ function check-count() {
   fi
 }
 
-
 ## Start testing suite
 
 docker compose up --build --remove-orphans --force-recreate -d
@@ -94,6 +99,19 @@ while ! docker compose exec db_server pg_isready ; do
   sleep 1
 done
 
+run-test "backup without a database name"
+in-container backup-db
+if (( $? == 0 )); then
+  echo "Database was backed up even though it should not be"
+  exit 1
+else
+  echo "failed to back up database"
+fi
+
+run-test "basic backup"
+
+export DB_NAME="test_database"
+
 docker compose exec db_server createdb $DB_NAME
 
 docker compose exec db_server psql $DB_NAME -c \
@@ -101,8 +119,6 @@ docker compose exec db_server psql $DB_NAME -c \
 INSERT INTO test_table (name) VALUES ('test');"
 
 echo "Created test database"
-
-run-test "basic backup"
 
 do-backup
 
