Some testing niceties

diff --git a/test-backup b/test-backup
--- a/test-backup
+++ b/test-backup
@@ -26,10 +26,18 @@ file_list=$(docker compose exec storage ls /data/test-bucket)
 docker compose down
 docker compose rm -f --volumes
 
+exit_status=0
 if [ -z "$file_list" ]; then
-  echo "No files found in S3 bucket"
-  exit 1
+  echo "No files found in S3 bucket."
+  exit_status=1
 else
   echo $file_list
   echo "Backup file saved successfully!"
+fi
+
+if (( $exit_status )); then
+  echo "Tests failed!"
+  exit $exit_status
+else
+  echo "Tests passed!"
 fi
