All tests pass

diff --git a/test-backup b/test-backup
--- a/test-backup
+++ b/test-backup
@@ -14,10 +14,9 @@ if [ ${1:-""} == "--no-cleanup" ]; then
   shift
 fi
 
-
 run-test() {
   echo ""
-  echo -e "\033[1mTesting $1\033[0m"
+  echo -e "\033[1mTest: $1\033[0m"
 }
 
 cleanup() {
@@ -41,9 +40,46 @@ cleanup() {
 trap "cleanup" EXIT
 
 export S3_BACKUP_BUCKET="test-bucket"
-export DB_BACKUP_PREFIX="test-backup"
 export DB_NAME="test_database"
 export PGPORT=5432
+
+function do-backup() {
+  # Run a backup and return the exit code
+  docker compose run db_backup backup-db
+  if [ $? -ne 0 ]; then
+    echo "Backup failed!"
+    exit 1
+  fi
+}
+
+function find-files() {
+  prefix=$1
+  file_list=$(docker compose exec --workdir /data/$S3_BACKUP_BUCKET storage find . -type f -path ./$prefix-*.pg-dump)
+  echo $file_list
+  # Test that a backup file was created
+  if [ -z "$file_list" ]; then
+    echo "No matching files found in S3 bucket."
+    exit 1
+  fi
+  echo $file_list
+}
+
+function check-count() {
+  # Check that the number of files in the S3 bucket matches the expected count
+  expected_count=$1
+  file_list=$(docker compose run -T db_backup find-remote-backups)
+  echo "$file_list"
+  n_files=$(echo "$file_list" | wc -l)
+  # Override for empty case
+  [ -z "$file_list" ] && n_files=0
+  if (( $n_files != $expected_count )); then
+    echo "Expected $expected_count file, found $n_files"
+    exit 1
+  fi
+}
+
+
+## Start testing suite
 
 docker compose up --build --remove-orphans --force-recreate -d
 
@@ -62,37 +98,37 @@ echo "Created test database"
 
 run-test "basic backup"
 
-docker compose run db_backup backup-db
-if [ $? -ne 0 ]; then
-  echo "Backup failed!"
-  exit 1
-fi
+do-backup
 
+prefix="$DB_NAME"
+
+file_list=$(find-files $prefix)
+check-count 1
+
+run-test "remove last backup"
+
+file_list=$(docker compose run -T db_backup find-remote-backups)
+last_backup=$(echo "$file_list" | tail -n 1)
+echo $last_backup
+docker compose run db_backup remove-remote-backup $last_backup
+check-count 0
+
+run-test "backup with prefix"
+
+export DB_BACKUP_PREFIX="test-backup"
 prefix="$DB_BACKUP_PREFIX/$DB_NAME"
+
+do-backup
+
 # Independently verify that the file is in the backend
-file_list=$(docker compose exec --workdir /data/$S3_BACKUP_BUCKET storage find . -type f -path ./$prefix-*.pg-dump)
+file_list=$(find-files $prefix)
 
-echo $file_list
-
-# Test that a backup file was created
-if [ -z "$file_list" ]; then
-  echo "No matching files found in S3 bucket."
-  exit 1
-fi
-
-echo "Backup file saved successfully!"
-
-run-test "correct number of backups"
-
-n_files=$(echo $file_list | wc -l)
-if (( $n_files != 1 )); then
-  echo "Expected 1 file, found $n_files"
-  exit 1
-fi
+check-count 1
 
 run-test "correct prefix"
 
-if [[ ! $file_list == "./$prefix-"* ]]; then
+echo "$file_list"
+if [[ ! $file_list == "$prefix-"* ]]; then
   echo "Backup file name does not match expected format."
   exit 1
 fi
@@ -108,16 +144,7 @@ fi
 
 run-test "list files using client API"
 
-echo ""
-file_list=$(docker compose run -T db_backup find-remote-backups)
-echo "$file_list"
-
-n_files=$(echo "$file_list" | wc -l)
-echo $n_files
-if (( $n_files != 2 )); then
-  echo "Expected 2 file, found $n_files"
-  exit 1
-fi
+check-count 2
 
 
 
